version: "3"

services:
    nginx:
        build:
            context: ./docker/nginx
        volumes:
            - ./:/var/www/symfony:cached
        ports:
            - "80:80"

    php:
        build:
            context: ./docker/php
        volumes:
            - ./:/var/www/symfony:cached

    db:
        image: mysql:8.0.33
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "mysql:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"

volumes:
    mysql:
